# Generated by Django 4.2.23 on 2025-06-13 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="People",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name="todo",
            name="people",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.RESTRICT,
                to="todos.people",
            ),
            preserve_default=False,
        ),
    ]
